# Generated by Django 4.1.6 on 2023-02-13 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
